### ISSUE TITLE
PyPI packages versions

### ISSUE THREAD

**Issue by drnextgis** [dezhin/pygdal#11]
Why PyPI index contains version numbers which consists of 4 group of numbers, e.g. `1.9.2.1`, `1.11.2.1` while names of directories within repository consists of 3: `1.9.1`, `1.11.2`. Is it correct?
I'm trying to update package and get get the folowing error:

```
Downloading/unpacking pygdal==1.11.2 (from nextgisweb==0.0)
  Could not find a version that satisfies the requirement pygdal==1.11.2 (from nextgisweb==0.0) (from versions: 1.10.0.0, 1.10.0.1, 1.10.1.0, 1.10.1.1, 1.11.0.0, 1.11.0.1, 1.11.1.0, 1.11.1.1, 1.11.2.1, 1.8.1.0, 1.8.1.1, 1.9.2.0, 1.9.2.1)
Cleaning up...
No distributions matching the version for pygdal==1.11.2 (from nextgisweb==0.0)
Storing debug log for failure in /home/rykov/.pip/pip.log
```

**Comment by dezhin** [comment]
Yes, it is correct. But it doesn't work as expected. Last number is for pygdal versioning. I increment it with changes in pygdal but not in gdal (python 3 for example). Unfortunately `pydgal==1.11.2` matches only `1.11.2.0`. So you can use `pygdal>=1.11.2,<1.11.3` to install latest pygdal version that matches your gdal version.
