### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by pwnage-pineapple** [dezhin/pygdal#12]
When trying to install with Pip, I get this:

````python
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-_84p0zuz/pygdal/setup.py", line 61
        print 'GDAL prefix from environment variable %s' % ENV_GDALHOME
                                                       ^
    SyntaxError: Missing parentheses in call to 'print'
````

**Comment by dezhin** [comment]
It looks like you are using an older version of pygdal which is not compatible with a python 3. How do you install it?

**Comment by pwnage-pineapple** [comment]
using pip for python 3, typing `sudo pip install pygdal`

**Comment by dezhin** [comment]
Sorry I forgot to upload latest versions with python 3 support to PyPi. But I did it now. Please try again. Don't forget to specify gdal version `pip install pygdal>=1.8.1.0,<=1.8.1.999` for GDAL 1.8.1 in example.

**Comment by auz9** [comment]
Hi. Wish I found this earlier.  Thanks.
Would like to add that with  __pyenv local 3.4.3__, running the above pip install spit  __No such file or directory__  in bash. 
This got my gears going again for  __libgdal-dev__ (GDAL) ver 1.10.1
```
pip install "pygdal>=1.10.1,<1.10.2"
```
