### ISSUE TITLE
Running pygdal 1.9.2 with Python 3.4.0?

### ISSUE THREAD

**Issue by nigelicusx** [dezhin/pygdal#14]
Hello, first off, thanks for maintaining this package. Do you have any suggestions regarding modifying this package to support GDAL 1.9.2 with Python 3.4.0? The web host I use has these packages installed and dus to issues with other apps and Py 2.7, I'm stuck at the moment in py2-py3 limbo. I've gotten setup.Py to install by replacing the code to build the paths to the GDAL libraries with the full system paths (otherwise I get a can't mix str and byutes in OS.path.join errors), but it looks like the actual c++ GDAL modules are not getting bound to Python correctly (I get errors using from osgeo import * etc in Python 3.4.0 like the osgeo functions can't be found). I'm guessing this is an issue with swig but I'm not sure.
Any help you can offer would be great! Thanks very much

**Comment by dezhin** [comment]
I do not understand what problem you have encountered. I just tried to install pygdal in python 3.4 and it looks like everything is working fine.

```
$ cd ~/tmp
$ virtualenv -p /usr/bin/python3.4 pygdalenv
$ cd ppygdaltmp/
$ . bin/activate
$ gdal-config --version
1.10.1
$ pip install "pygdal>=1.10.1,<1.10.1.999"
$ python -c "from osgeo import ogr"
$ python
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal, ogr, osr
>>> dir(gdal)
['AllRegister', 'ApplyGeoTransform', 'AsyncReader', ...]
```

**Comment by nigelicusx** [comment]
Thanks for your reply. Here's my terminal output (on red hat):
[ code ]  File "/home/ismappin/ismpenv34/build/pygdal/setup.py", line 61, in finalize_options

    self.library_dirs.append(os.path.join(self.gdaldir, 'lib'))

  File "/home/ismappin/ismpenv34/lib/python3.4/posixpath.py", line 92, in join

    "components.") from None

TypeError: Can't mix strings and bytes in path components. [  /code ]

**Comment by nigelicusx** [comment]
Sorry about that code-block mess.

```
  File "/home/ismappin/ismpenv34/build/pygdal/setup.py", line 61, in finalize_options

    self.library_dirs.append(os.path.join(self.gdaldir, 'lib'))

  File "/home/ismappin/ismpenv34/lib/python3.4/posixpath.py", line 92, in join

    "components.") from None

TypeError: Can't mix strings and bytes in path components.

```
The command I issued in my Py3.4.0 virtualenv was:
```
$ gdal-config --version
1.9.2

$pip install "pygdal==1.9.2"
```

**Comment by dezhin** [comment]
You can try use pip this way:

    $ pip install "pygdal>=1.9.2,<1.9.2.999"

**Comment by nigelicusx** [comment]
Wow, I feel dumb. Thanks I didn't realize pip should be invoked that way, which grabbed v 1.9.2.3

Looks like everything's working fine, thanks very much for your time and help!
