### ISSUE TITLE
Please add support for GDAL 1.11.5

### ISSUE THREAD

**Issue by jwm** [dezhin/pygdal#16]
Hi Aleksandr, thanks for writing pygdal! We use it often, to parse shapefiles of real estate data.

Would you add support for GDAL 1.11.5, please? It was released recently.

**Comment by drnextgis** [comment]
PR https://github.com/dezhin/pygdal/pull/17

**Comment by dezhin** [comment]
Just uploaded version 1.11.5 to PyPi.

**Comment by jwm** [comment]
Thanks!
