### ISSUE TITLE
GDAL 2.2.0

### ISSUE THREAD

**Issue by youngpm** [dezhin/pygdal#25]
I've got a PR coming that adds 2.2 to the build!

**Comment by drnextgis** [comment]
@youngpm please update your files with [impfix](https://github.com/dezhin/pygdal/blob/master/impfix).

**Comment by youngpm** [comment]
@drnextgis I did before submitting the PR, should be good to go!

**Comment by drnextgis** [comment]
Strange, [here](https://github.com/youngpm/pygdal/blob/618f4372ab2f94c3949e333b526c31aa49a127b8/2.2.0/osgeo/gdal.py#L2016) should be:

```
from osgeo import gdalnumeric
```

**Comment by youngpm** [comment]
@drnextgis you're right; OSX's sed is broken in some way where the regex wasn't matching on the ones with actual white space in front; installing the GNU version off of Brew fixed it!  I've updated the PR.

**Comment by dezhin** [comment]
I've hust merged PR and uploaded new version to PyPI.
