### ISSUE TITLE
Add support for version 1.11.2 of GDAL

### ISSUE THREAD

**Issue by rutsky** [dezhin/pygdal#6]
Ubuntu 15.04, that will be released in a few days, will have GDAL 1.11.2.

**Comment by dezhin** [comment]
Added in 6e4bbdf and uploaded to PyPi. Please test it.

**Comment by rutsky** [comment]
@dezhin Are you sure that you uploaded 6e4bbdf ?
I see, that at least this commit https://github.com/dezhin/pygdal/commit/b9869dfc7640630631f8c6ae8400383680dfd5b4 (that fixes installation on Python 3) is not in [1] on PyPI [2].

[1] https://pypi.python.org/packages/source/p/pygdal/pygdal-1.11.2.1.tar.gz#md5=f6a9b6fca1e841e58dd0641bdc942f61

[2] https://pypi.python.org/pypi/pygdal/1.11.2.1

**Comment by dezhin** [comment]
Sorry, It was a typo in the comment. I had not planned to upload commit 6e4bbdf. I don't know is it enough for python 3 support. So I have uploaded b1b8ed81acfd070d7db8e8f71d742a9b325fac58

**Comment by rutsky** [comment]
b9869df is required for Python 3: `print` without braces will not work in Python 3 and `check_output` by default returns `bytes`.

**Comment by dezhin** [comment]
I understand that this commit is required. But is it *enough* for use this package with python 3?

**Comment by rutsky** [comment]
I think *almost* enough :) I have problem with `import osr` that I have reported (https://github.com/dezhin/pygdal/issues/8). If I remove `import osr` from ogr.py at least ogr+osr works (I managed to read Shapefile).
