### ISSUE TITLE
Invalid "import osr"

### ISSUE THREAD

**Issue by rutsky** [dezhin/pygdal#8]
Is this `import osr` correct and needed?

https://github.com/dezhin/pygdal/blob/master/1.11.2/osgeo/ogr.py#L143

As I see, pygdal doesn't create root-level `osr` module (and shouldn't, since `osr` is obsoleted in favor of `osgeo.osr`, AFAIK).
Or pygdal does some magic with `sys.path` that I missed?

**Comment by dezhin** [comment]
This files are copied from gdal tar-ball "as-is". Maybe `import osr` not needed - there are not direct references to `osr` in ogr.py. But it can use some import side effect.

There are no magic with `sys.path` and this import works because file osr.py located in same directory.

**Comment by rutsky** [comment]
When I install pygdal it adds to sys.path directory, that contains `osgeo` directory, so that I can do

```
import osgeo
```

But `osgeo/` directory is not in `sys.path`, so files from `osgeo/` directory cannot be imported in a `import osr` way — they may be imported as `import osgeo.osr` or as relative import, e.g. from `ogr.py`: `from . import osr`.

I think `import osr` shouldn't work.

**Comment by dezhin** [comment]
But it works for me and other people using this package... It shouldn't work in files outside `osgeo/`. There are no `from __future__ import absolute_import` in `ogr.py` and relative import works in this case.

**Comment by rutsky** [comment]
I prepared Travis configuration that will allow to run pygdal tests in Python 3.3: https://github.com/dezhin/pygdal/pull/9

Here is the result of installing current master of pygdal on Ubuntu 12.04 with GDAL from 15.04 (1.11.2) and running `python -c "from osgeo import gdal, ogr, osr"`: https://travis-ci.org/rutsky/pygdal

With Python 2.7 all ok: https://travis-ci.org/rutsky/pygdal/jobs/62488515
With Python 3.4 `osgeo/gdal.py` can't import `gdalconst` (that is located in `osgeo` directory): https://travis-ci.org/rutsky/pygdal/jobs/62488516

I vote for gdal doing some tricks with `sys.path`:)

**Comment by rutsky** [comment]
In my Ubuntu 14.04 system version of python3-gdal package installs:

```
...
/usr/lib/python3/dist-packages/gdal.py
/usr/lib/python3/dist-packages/ogr.py
/usr/lib/python3/dist-packages/gdalconst.py
/usr/lib/python3/dist-packages/osgeo
/usr/lib/python3/dist-packages/osgeo/gdal.py
/usr/lib/python3/dist-packages/osgeo/ogr.py
/usr/lib/python3/dist-packages/osr.py
/usr/lib/python3/dist-packages/gdalnumeric.py
/usr/lib/python3/dist-packages/osgeo/gdal_array.py
/usr/lib/python3/dist-packages/osgeo/__init__.py
/usr/lib/python3/dist-packages/osgeo/gdalconst.py
/usr/lib/python3/dist-packages/osgeo/osr.py
/usr/lib/python3/dist-packages/osgeo/gdalnumeric.py
...
```

and root level `osr.py`, `gdal.py` etc. has contents like:

```
# import osgeo.gdal as a convenience
from osgeo.gdal import deprecation_warn
deprecation_warn('gdal')

from osgeo.gdal import *
```

So on system level there is no magic with `sys.path`.

**Comment by rutsky** [comment]
I missed your comment about `absolute_import`: yes, you right, and importing `osr.py` from `osgeo/ogr.py` should work on Python < 3.0, but not on Python 3.

**Comment by dezhin** [comment]
I've changed relative imports to absolute. It should fix this issue.

**Comment by shaunstoltz** [comment]
ImportError: libncurses.so.6: cannot open shared object file: No such file or directory

**Comment by ditafaith** [comment]
Hi, 

Is there any advise on how to solve the problem like this ?
I make sure that I installed GDAL.

```
raise ImportError('Cannot import gdal and osr!')
ImportError: Cannot import gdal and osr
```
